[package]
name = "rust_sqlite"
version = "0.36.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = [
    "runtime-async-std-native-tls",
    "sqlite",
] }
async-std = { version = "1.6", features = ["attributes"] }
futures = "0.3.18"
